// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Gen$ReasonGenPractice = require("../src/gen/Gen.bs.js");

function naturalNumbers(param) {
  var n = {
    contents: 1
  };
  return function (param) {
    var cur = n.contents;
    n.contents = n.contents + 1 | 0;
    return cur;
  };
}

var nats = naturalNumbers(undefined);

var firstTen = Gen$ReasonGenPractice.take(10, nats);

console.log(firstTen(undefined));

function iter(f, theList) {
  var _l = theList;
  while(true) {
    var l = _l;
    if (!l) {
      return ;
    }
    Curry._1(f, l.hd);
    _l = l.tl;
    continue ;
  };
}

var result = {
  contents: /* [] */0
};

function f(x) {
  result.contents = {
    hd: x,
    tl: result.contents
  };
  console.log(result);
  
}

iter(f, {
      hd: "a",
      tl: {
        hd: "b",
        tl: {
          hd: "c",
          tl: /* [] */0
        }
      }
    });

var result$1 = {
  contents: /* [] */0
};

function f$1(x) {
  result$1.contents = {
    hd: x,
    tl: result$1.contents
  };
  console.log(result$1.contents);
  
}

iter(f$1, {
      hd: "a",
      tl: {
        hd: "b",
        tl: {
          hd: "c",
          tl: {
            hd: "d",
            tl: /* [] */0
          }
        }
      }
    });

exports.naturalNumbers = naturalNumbers;
exports.nats = nats;
exports.firstTen = firstTen;
exports.iter = iter;
exports.result = result$1;
exports.f = f$1;
/* nats Not a pure module */
